### ISSUE TITLE
backtrace printings

### ISSUE THREAD

**Issue by gobftald** [esp-rs/esp-backtrace#52]
May be I'm wrong but I cannot really understand the next code fragment in lib.rs:98

            #[cfg(all(feature = "colors", feature = "println"))]
            println!("{}0x{:x}", RED, addr - crate::arch::RA_OFFSET);

!!!!!       #[cfg(not(any(feature = "colors", feature = "println")))]
            println!("0x{:x}", addr - crate::arch::RA_OFFSET);

If it wants to differentiate between the "colors" and not "colors" scenario, I think it's wrong. The second #[cfg... gives false in case of no"colors", printing nothing in that case.

I think the proper #[cfg... would be:

            #[cfg(all(not(feature = "colors"), feature = "println"))]
            println!("0x{:x}", addr - crate::arch::RA_OFFSET);

But I'm quite a newbie, so may be I'm wrong and misunderstood something.

**Comment by bjoernQ** [comment]
Thanks! There were indeed a few problems when using unusual feature combinations 👍 Hopefully the changed CI workflow will help in preventing similar things in future
